"use client";

import React, { useState } from "react";
import { Save } from "lucide-react";
import type { Category, ProductInsert, Warehouse } from "@/types/database.types";
import BarcodeDisplay from "@/components/products/BarcodeDisplay";
import { createProduct, getCategoryFullName } from "@/lib/products/api";
import { useI18n } from "@/i18n/I18nProvider";

interface ProductFormProps {
  categories: Category[];
  warehouses: Warehouse[];
  onSuccess?: () => void;
  onCancel?: () => void;
}

const UNITS = ["Ədəd", "Kq", "Litr", "Metr", "Qutu"];

export default function ProductForm({
  categories,
  warehouses,
  onSuccess,
  onCancel,
}: ProductFormProps) {
  const { t } = useI18n();
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({
    code: "",
    name: "",
    category: categories[0]?.name || "",
    subcategory: "",
    unit: "Ədəd",
    buy_price: "0",
    sell_price: "0",
    stock: "0",
    min_stock: "5",
    barcode: "",
    color: "",
    weight: "0",
    extra_info: "",
    warehouse_id: warehouses[0]?.id || "",
  });

  const set = (patch: Partial<typeof form>) => setForm((prev) => ({ ...prev, ...patch }));

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!form.name.trim()) {
      alert(t("forms.enterProductName"));
      return;
    }

    setSaving(true);
    const payload: ProductInsert = {
      code: form.code,
      name: form.name,
      category: form.category || "Ümumi",
      subcategory: form.subcategory || null,
      unit: form.unit,
      buy_price: parseFloat(form.buy_price) || 0,
      sell_price: parseFloat(form.sell_price) || 0,
      stock: parseFloat(form.stock) || 0,
      min_stock: parseFloat(form.min_stock) || 0,
      barcode: form.barcode || null,
      color: form.color || null,
      weight: parseFloat(form.weight) || 0,
      extra_info: form.extra_info || null,
    };

    const result = await createProduct(payload);
    setSaving(false);

    if (!result.ok) {
      alert(t("common.errorOccurred", { message: result.error ?? t("common.error") }));
      return;
    }

    alert(t("forms.productCreated"));
    onSuccess?.();
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-5 app-card app-card-elevated p-6">
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        <label className="block text-xs font-semibold text-app">
          {t("forms.productCode")}
          <input
            type="text"
            value={form.code}
            onChange={(e) => set({ code: e.target.value })}
            placeholder={t("forms.autoGenerated")}
            className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"
          />
        </label>

        <label className="block text-xs font-semibold text-app">
          {t("forms.productName")}
          <input
            type="text"
            required
            value={form.name}
            onChange={(e) => set({ name: e.target.value })}
            className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"
          />
        </label>

        <label className="block text-xs font-semibold text-app">
          {t("common.category")} *
          <select
            required
            value={form.category}
            onChange={(e) => set({ category: e.target.value })}
            className="app-input mt-1 text-sm"
          >
            <option value="">{t("common.select")}</option>
            {categories.map((c) => (
              <option key={c.id} value={c.name}>
                {getCategoryFullName(categories, c)}
              </option>
            ))}
          </select>
        </label>

        <label className="block text-xs font-semibold text-app">
          {t("forms.subcategory")}
          <input
            type="text"
            value={form.subcategory}
            onChange={(e) => set({ subcategory: e.target.value })}
            className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"
          />
        </label>

        <label className="block text-xs font-semibold text-app">
          {t("common.warehouse")}
          <select
            value={form.warehouse_id}
            onChange={(e) => set({ warehouse_id: e.target.value })}
            className="app-input mt-1 text-sm"
          >
            <option value="">{t("forms.notSelected")}</option>
            {warehouses.map((w) => (
              <option key={w.id} value={w.id}>
                {w.name}
              </option>
            ))}
          </select>
        </label>

        <label className="block text-xs font-semibold text-app">
          {t("forms.unitMeasure")}
          <select
            value={form.unit}
            onChange={(e) => set({ unit: e.target.value })}
            className="app-input mt-1 text-sm"
          >
            {UNITS.map((u) => (
              <option key={u} value={u}>
                {u}
              </option>
            ))}
          </select>
        </label>

        <label className="block text-xs font-semibold text-app">
          {t("forms.buyPrice")} (AZN)
          <input
            type="number"
            step="0.01"
            value={form.buy_price}
            onChange={(e) => set({ buy_price: e.target.value })}
            className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"
          />
        </label>

        <label className="block text-xs font-semibold text-app">
          {t("forms.sellPrice")}
          <input
            type="number"
            step="0.01"
            value={form.sell_price}
            onChange={(e) => set({ sell_price: e.target.value })}
            className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"
          />
        </label>

        <div className="block text-xs font-semibold text-app">
          <label>
            {t("forms.barcode")}
            <input
              type="text"
              value={form.barcode}
              onChange={(e) => set({ barcode: e.target.value })}
              className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"
            />
          </label>
          {form.barcode.trim() && (
            <div className="mt-3 rounded-lg border border-app bg-app-card-hover p-3">
              <p className="mb-2 text-[10px] font-bold uppercase tracking-wide text-app-muted">
                {t("forms.barcodePreview")}
              </p>
              <BarcodeDisplay value={form.barcode} />
            </div>
          )}
        </div>

        <label className="block text-xs font-semibold text-app">
          {t("forms.color")}
          <input
            type="text"
            value={form.color}
            onChange={(e) => set({ color: e.target.value })}
            className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"
          />
        </label>

        <label className="block text-xs font-semibold text-app">
          {t("forms.weight")}
          <input
            type="number"
            step="0.001"
            value={form.weight}
            onChange={(e) => set({ weight: e.target.value })}
            className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"
          />
        </label>

        <label className="block text-xs font-semibold text-app">
          {t("forms.initialStock")}
          <input
            type="number"
            value={form.stock}
            onChange={(e) => set({ stock: e.target.value })}
            className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"
          />
        </label>

        <label className="block text-xs font-semibold text-app">
          {t("forms.minStockThreshold")}
          <input
            type="number"
            value={form.min_stock}
            onChange={(e) => set({ min_stock: e.target.value })}
            className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"
          />
        </label>
      </div>

      <label className="block text-xs font-semibold text-app">
        {t("forms.extraInfo")}
        <textarea
          rows={3}
          value={form.extra_info}
          onChange={(e) => set({ extra_info: e.target.value })}
          className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"
        />
      </label>

      <div className="flex justify-end gap-2 border-t border-app pt-4">
        {onCancel && (
          <button
            type="button"
            onClick={onCancel}
            className="rounded-lg border px-4 py-2 text-xs font-semibold text-app"
          >
              {t("common.cancel")}
          </button>
        )}
        <button
          type="submit"
          disabled={saving}
          className="flex items-center gap-1 rounded-lg bg-blue-600 px-5 py-2 text-xs font-bold text-white disabled:opacity-50"
        >
          <Save className="h-4 w-4" />
          {saving ? t("common.saving") : t("forms.saveProduct")}
        </button>
      </div>
    </form>
  );
}
