"use client";

import { useState } from "react";
import { Printer, RefreshCw } from "lucide-react";
import BarcodeDisplay from "@/components/products/BarcodeDisplay";
import PrintableLabelArea from "@/components/products/PrintableLabelArea";
import ThermalLabelPrintTemplate, {
  type ThermalLabelItem,
} from "@/components/products/ThermalLabelPrintTemplate";
import { isEan13Payload, type BarcodeLabelConfig } from "@/lib/barcode/labelConfig";
import { generateProductBarcode } from "@/lib/products/generateBarcode";
import { formInputClass, formSelectClass } from "@/components/ui/form-field-styles";
import Button from "@/components/ui/button";
import { useBarcodeLabelConfig } from "@/hooks/useBarcodeLabelConfig";
import { useCompanyBranding } from "@/hooks/useCompanyBranding";
import { useDocumentPrint } from "@/hooks/useDocumentPrint";
import { useI18n } from "@/i18n/I18nProvider";

export const FORM_LABEL_SIZES = [
  { id: "50x30mm", widthMm: 50, heightMm: 30 },
  { id: "40x25mm", widthMm: 40, heightMm: 25 },
] as const;

export type FormLabelSizeId = (typeof FORM_LABEL_SIZES)[number]["id"];

interface ProductBarcodePanelProps {
  value: string;
  onChange: (value: string) => void;
  productName?: string;
  productCode?: string;
  sellPrice?: number | null;
}

function resolveBarcodeFormat(code: string): "CODE128" | "EAN13" {
  return isEan13Payload(code) ? "EAN13" : "CODE128";
}

function buildPrintConfig(
  base: BarcodeLabelConfig,
  labelSize: FormLabelSizeId,
  barcode: string
): BarcodeLabelConfig {
  const selected = FORM_LABEL_SIZES.find((size) => size.id === labelSize) ?? FORM_LABEL_SIZES[0];
  return {
    ...base,
    paper_size: "CUSTOM",
    custom_width_mm: selected.widthMm,
    custom_height_mm: selected.heightMm,
    barcode_type: resolveBarcodeFormat(barcode),
  };
}

export default function ProductBarcodePanel({
  value,
  onChange,
  productName = "",
  productCode = "",
  sellPrice = null,
}: ProductBarcodePanelProps) {
  const { t } = useI18n();
  const branding = useCompanyBranding();
  const { config: labelConfig } = useBarcodeLabelConfig();
  const [labelSize, setLabelSize] = useState<FormLabelSizeId>("50x30mm");
  const { printData, setPrintData } = useDocumentPrint<{
    items: ThermalLabelItem[];
    config: BarcodeLabelConfig;
  }>(450);

  const code = value.trim();
  const barcodeFormat = resolveBarcodeFormat(code);

  const handlePrint = () => {
    if (!code) return;
    const item: ThermalLabelItem = {
      id: "draft-product",
      name: productName.trim() || t("forms.productName"),
      code: productCode.trim() || null,
      barcode: code,
      price: sellPrice,
    };
    setPrintData({
      items: [item],
      config: buildPrintConfig(labelConfig, labelSize, code),
    });
  };

  return (
    <>
      <div className="flex min-w-0 flex-wrap items-center gap-2 rounded-[var(--erp-radius-md)] border border-[color:var(--erp-border-default)] bg-[color:var(--erp-bg-table-header)]/30 p-2">
        <input
          type="text"
          value={value}
          onChange={(event) => onChange(event.target.value)}
          placeholder={t("forms.autoGenerated")}
          className={`${formInputClass} min-w-[8rem] flex-1 font-mono text-sm`}
          aria-label={t("forms.barcode")}
        />
        <Button
          type="button"
          variant="outline"
          size="sm"
          className="shrink-0"
          onClick={() => onChange(generateProductBarcode())}
        >
          <RefreshCw className="h-3.5 w-3.5" />
          {t("inventory.generateBarcode")}
        </Button>
        <select
          value={labelSize}
          onChange={(event) => setLabelSize(event.target.value as FormLabelSizeId)}
          className={`${formSelectClass} w-auto min-w-[6.5rem] shrink-0 py-2 text-xs`}
          aria-label={t("forms.barcodePanelLabelSize")}
        >
          {FORM_LABEL_SIZES.map((size) => (
            <option key={size.id} value={size.id}>
              {t(`forms.labelSizes.${size.id}`)}
            </option>
          ))}
        </select>
        <Button
          type="button"
          variant="outline"
          size="sm"
          className="shrink-0"
          onClick={handlePrint}
          disabled={!code}
        >
          <Printer className="h-3.5 w-3.5" />
          {t("forms.printBarcode")}
        </Button>
        {code ? (
          <div
            className="ml-auto inline-flex shrink-0 items-center justify-center rounded border border-dashed border-[color:var(--erp-border-default)] bg-white px-1.5 py-1"
            aria-hidden
          >
            <BarcodeDisplay
              value={code}
              format={barcodeFormat}
              width={0.7}
              height={16}
              fontSize={6}
              showValue
            />
          </div>
        ) : null}
      </div>

      {printData ? (
        <PrintableLabelArea>
          <ThermalLabelPrintTemplate
            items={printData.items}
            config={printData.config}
            branding={branding}
          />
        </PrintableLabelArea>
      ) : null}
    </>
  );
}
